# Message file path
message-file: "%datafolder%/messages/en-US.yml"

curve:
  # Fineness of the curve
  fineness: 10
  # Maximum length a curve can be built
  max-set-length: 10000
  # Maximum value of pos that can be set with the pos command
  max-pos-value: 100
  # If this value is true, the center will be thicker
  thicken-center: false
  # Default maximum block change limit for CurveBuilding
  # If this value is -1, it means unlimited
  default-max-change-limit: 10000000

particles:
  pos:
    # Particle color
    color:
      pos: 0x00FFFF
      start_pos: 0xFF00FF
      end_pos: 0xFFFF00
      f: 0xFF0077
      b: 0x7700FF

    # Particle density per block
    density: 4

  line:
    # Particle density per block
    density: 4
    # Maximum length to display particles
    max-length: 10000